### ISSUE TITLE
Mal for Oppgaver

### ISSUE THREAD

**Issue by FSvnsn** [FSvnsn/AndroidProsjekt#1]
| Valg av tittel |
|:----------|
|_Denne skal være relativt enkel å forstå, det må selvfølgelig være en standard dere setter opp_; |
|Eksempelvis: `Hva Som Skal Gjøres (Tilhørende Prosjekt)` Label label label|
| **Notat:** Gjerne gjør denne om til engelsk om dere vil|
## Oppgavetittel
_Kort hva denne oppgaven dreier seg om._

| Notat|
|:----------|
| Dere må huske på å sette rett assignee, merke den med riktige labels og feste den til rett prosjekttype. Ikke glem å legge den i tilvalgt sprint (milestone)   |

### Oppgaver for denne Tasken
- [ ] Deloppgave 1 (les mer om denne oppgaven her: #26)
- [ ] Deloppgave 2 (les mer om denne oppgaven her: #26)
- [ ] Deloppgave 3 (les mer om denne oppgaven her: #26)
- [ ] Deloppgave 4 (les mer om denne oppgaven her: #26)
_Det er verdt å notere seg at deloppgavene skal være like gjennomtenkte. De skal reflektere user stories e.l. fra boka hvor dette er nødvendig._
### Beskrivelse
_Her skriver dere en utfyllende beskrivelse av problemet som skal løses. Gjerne med linker til stoff og sider i bøker som er nødvendig for å løse oppgaven. Videre kan der være lurt å utarbeide noe enkel grafikk som illustrerer problemet._

### Løsningsforslag
_Her skriver dere (over tid) det som blir fremarbeidet gjennom oppgaven som er beskrevet, på en slik måte at det kan benyttes til en eventuell rapport. Om dette er en oppgave som ikke skal inn i rapporten, så skal det skrives en rapport her om hvordan det ble løst og hva som ble gjort, samt resultatet av det som ble gjort._

### Ekstra informasjon
_Her kan dere skrive ekstra informasjon som kan være nødvendig for å forstå denne oppgaven. Det kan også være [linker](google.com) eller vedlegg._
